language: python

dist: xenial

env:
  - CODECOV_TOKEN=$CODECOV

matrix:
    include:
      - python: 3.5
      - python: 3.6
      - python: 3.7

install:
  - make install

before_script:
  - make flake8

script: 
  - make test

after_success:
  - codecov

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
    repo: mstuttgart/pycep-correios
