name: Coverage Report

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

    - name: Unit tests
      run: |
        pytest --cov=pycep_correios

    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Report

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
